# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_artile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='artile_image',
            new_name='article_image',
        ),
    ]
